select
    _file as "source_file",
    _line as "record_line_no",
    _modified as "updated_at",
    _fivetran_synced as "loaded_at",
    interaction_id as "interaction_id",
    customer_id as "customer_id",
    order_id as "order_id",
    product_id as "product_id",
    interaction_at as "interaction_at",
    channel as "channel",
    interaction_type as "interaction_type",
    issue_category as "issue_category",
    sentiment_score as "sentiment_score",
    sentiment_label as "sentiment_label",
    csat_score as "csat_score",
    resolved_flag as "resolved_flag",
    resolution_minutes as "resolution_minutes",
    follow_up_required as "follow_up_required",
    interaction_cost as "interaction_cost",
    refund_amount as "refund_amount",
    support_agent_id as "support_agent_id",
    interaction_summary as "interaction_summary"
from {{ source('raw', 'customer_support_interactions') }}
